---
- hosts: deploy2
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
   - side: 2
  roles:
   - role: status_side

- hosts: deploy1
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
   - side: 1
  roles:
   - role: nag_apa_bal

- hosts: deploy1
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
   - side: 1
  roles:
   - role: status_side


- hosts: deploy2
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
   - side: 2
  roles:
   - role: nag_apa_bal
